AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Application for outbound messages for relying parties

Parameters:
  Environment:
    Description: Name of Environment to deploy to
    Type: String
    Default: build
    AllowedValues:
      - development
      - build
      - staging
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"
  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"
  VpcStackName:
    Type: "String"
    Description: "The name of the stack that defines the VPC to use"
  BranchName:
    Type: String
    Description: "Name of the branch to be deployed"
    Default: "main"

Conditions:
  UseCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, "none"]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, "none"]]

Globals:
  Function:
    Runtime: nodejs20.x
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    Timeout: 30
    Tracing: Active
    Architectures:
      - arm64
    Environment:
      Variables:
        LOG_LEVEL: DEBUG
        POWERTOOLS_SERVICE_NAME: RPR
        POWERTOOLS_METRICS_NAMESPACE: !Sub ${Environment}-RPR
        POWERTOOLS_TRACE_ENABLED: true
        POWERTOOLS_TRACER_CAPTURE_HTTPS_REQUESTS: true

Resources:
  ##############################################################
  # Receiver Lambda
  ##############################################################
  ReceiverFunction:
    #checkov:skip=CKV_AWS_116: Lambda level DLQs not supported with SQS / Api Gateway Triggers. DLQs at Queue level instead
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      Environment:
        Variables:
          LAMBDA_NAME: ReceiverLambda
          VALIDATOR_QUEUE_URL: !Ref ValidateEventQueue
      FunctionName: !Sub ${Environment}-${AWS::StackName}-event-receiver
      Description: performs basic payload validation to confirm POST request payload is structured correctly in Base64 strings
      CodeUri: src/lambdas/receiver-lambda
      Handler: handler.handler
      MemorySize: 128
      KmsKeyArn: !GetAtt LambdaKeyStore.Arn
      ReservedConcurrentExecutions: 10
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdB
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-AWSServicesEndpointSecurityGroupId
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ValidateEventQueue.QueueName
        - KMSEncryptPolicy:
            KeyId: !Ref QueueKeyStore
        - KMSDecryptPolicy:
            KeyId: !Ref QueueKeyStore
        - KMSDecryptPolicy:
            KeyId: !Ref LambdaKeyStore
        - Statement:
            Sid: queueKeyPermissions
            Effect: Allow
            Action:
              - kms:GenerateDataKey
            Resource: !GetAtt QueueKeyStore.Arn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        EntryPoints:
          - handler.ts

  ReceiverLambdaLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ReceiverFunction}"
      KmsKeyId: !GetAtt LogKeyStore.Arn
      RetentionInDays: 30

  ##############################################################
  # Validate Event Queue
  ##############################################################
  ValidateEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref QueueKeyStore
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ValidateEventDeadLetterQueue.Arn
        maxReceiveCount: 5

  ##############################################################
  # Validate Event Dead Letter Queue
  ##############################################################
  ValidateEventDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref QueueKeyStore

  ##############################################################
  # Encryption Keys
  ##############################################################
  QueueKeyStore:
    Type: AWS::KMS::Key
    Properties:
      Description: Encryption key for Queues
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

  LogKeyStore:
    Type: AWS::KMS::Key
    Properties:
      Description: Encryption key for Logs
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action: "kms:*"
            Resource: "*"

  LambdaKeyStore:
    Type: AWS::KMS::Key
    Properties:
      Description: Encryption key for Lambda Variables
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
