AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Application for outbound messages for relying parties

Parameters:
  Environment:
    Description: Name of Environment to deploy to
    Type: String
    Default: build
    AllowedValues:
      - development
      - build
      - staging
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"
  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"
  VpcStackName:
    Type: "String"
    Description: "The name of the stack that defines the VPC to use"
  BranchName:
    Type: String
    Description: "Name of the branch to be deployed"
    Default: "main"
  DownloadTableName:
    Type: "String"
    Description: "Table name of the DynamoDB used for Download flow"
    Default: "download-table"

Conditions:
  OnMainBranch: !Or
    - !Equals [!Ref BranchName, "main"]
    - !Not [!Equals [!Ref Environment, development]]
  isNotProduction: !Not [!Equals [!Ref Environment, "production"]]
  ShouldMapApi: !And
    - !Condition isNotProduction
    - !Condition OnMainBranch

  IsStagingIntegrationProdEnv: !Or
    - !Equals [!Ref Environment, staging]
    - !Equals [!Ref Environment, integration]
    - !Equals [!Ref Environment, production]

  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

  UseProvisionedConcurrency:
    Fn::Not:
      - Fn::Equals:
          - !FindInMap [
              ProvisionedConcurrency,
              !Ref Environment,
              ProvisionedConcurrencyInstances,
            ]
          - 0

Globals:
  Function:
    Runtime: nodejs20.x
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    Timeout: 30
    Tracing: Active
    Architectures:
      - arm64
    Environment:
      Variables:
        NEW_FORMAT_QUEUE_URL: !Ref NewStandardQueue
        REFORMAT_QUEUE_URL: !Ref EventReformatQueue
        LOG_LEVEL: INFO
        POWERTOOLS_SERVICE_NAME: inboundSSF
        POWERTOOLS_METRICS_NAMESPACE: !Sub ${Environment}-InboundSSF
        AWS_LAMBDA_EXEC_WRAPPER: /opt/dynatrace
        DT_CONNECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_CONNECTION_BASE_URL: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_CLUSTER_ID: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_LOG_COLLECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_TENANT: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}"
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: "true"
        AWS_XRAY_CONTEXT_MISSING: "IGNORE_ERROR"
    AutoPublishAlias: live
    ProvisionedConcurrencyConfig:
      Fn::If:
        - UseProvisionedConcurrency
        - ProvisionedConcurrentExecutions:
            !FindInMap [
              ProvisionedConcurrency,
              !Ref Environment,
              ProvisionedConcurrencyInstances,
            ]
        - !Ref "AWS::NoValue"
    Layers:
      - !Sub
        - "{{resolve:secretsmanager:${SecretArn}:SecretString:NODEJS_LAYER}}"
        - SecretArn:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              dynatraceSecretArn,
            ]
  Api:
    OpenApiVersion: 3.0.1

Mappings:
  TxmaAccountIds:
    Environment:
      development: "604477301065" #di-fraud-ssf-dev account (TxMA Integration from Staging on)
      build: "250353618339" #di-fraud-ssf-build account (TxMA Integration from Staging on)
      staging: "178023842775"
      integration: "729485541398"
      production: "451773080033"
  ProvisionedConcurrency:
    production:
      ProvisionedConcurrencyInstances: 0
    staging:
      ProvisionedConcurrencyInstances: 0
    integration:
      ProvisionedConcurrencyInstances: 0
    build:
      ProvisionedConcurrencyInstances: 0
    development:
      ProvisionedConcurrencyInstances: 0
    local:
      ProvisionedConcurrencyInstances: 0

  PairwiseTableName:
    Environment:
      development: pairwise-mapping-table #Use our Mock Table for Dev and Build
      build: pairwise-mapping-table #Use our Mock Table for Dev and Build
      staging: "rp-events-infra-staging-rp-pairwise-mapping-table"
      integration: "rp-events-infra-integration-rp-pairwise-mapping-table"
      production: "rp-events-infra-production-rp-pairwise-mapping-table"

  PairwiseTableArns:
    Environment:
      development: "arn:aws:iam::604477301065:role/rp-main-pairwise-table-role" #Use our Mock Table Role for Dev and Build
      build: "arn:aws:iam::250353618339:role/mock-rp-service-pairwise-table-role" #Use our Mock Table Role for Dev and Build
      staging: "arn:aws:iam::260140483106:role/rp-events-infra-pairwise-table-access-role"
      integration: "arn:aws:iam::168392494868:role/rp-events-infra-pairwise-table-access-role"
      production: "arn:aws:iam::552549398917:role/rp-events-infra-pairwise-table-access-role"

  TxMAEndpointIds:
    Environment:
      development: "vpce-00916e3aedca26ff4" # use test-functions for dev and build
      build: "vpce-0910f1ba3c1cd91b8" # use test-functions for dev and build
      staging: "vpce-06ff38b49fa5472c8"
      integration: "vpce-089dfc6fa150ecbc2"
      production: "vpce-0090dd77e847c9d77"

  ##############################################################
  # Dynatrace
  ##############################################################

  EnvironmentConfiguration:
    development:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    build:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    staging:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    integration:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    production:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceProductionVariables

Resources:
