export enum ErrorMessages {
  DecryptCommandEmptyPlainText = "Empty Plaintext property returned",
  FailedToSendAll = "Failed to send all messages in batch",
  InvalidSQSResponse = "Invalid response received from SQS client",
  JWSNotVerified = "Previous logged JWS not verified",
  KMSPublicKeyUndefined = "KMS Public Key is not defined",
  LostMessage = "Some messages were lost in the SQS Send Batch Request",
  MissingRequiredFields = "Event missing required fields: ",
  NoBody = "No Body in Request",
  NoCredentials = "No Credentials Received",
  NoEvent = "Could not determine Event Type",
  NoEventsBlock = "No events block in SET",
  NoItems = "No items to be parsed",
  NoMessages = "There are no messages passed through",
  NoPairwiseId = "No matching Pairwise Id",
  NoQueueUrl = "Queue URL not Available",
  NoRecords = "No Records in Request",
  NoSubjectEvent = "No subject event found in events block of SET",
  NoTableName = "No Table Name Available",
  NoUserRecordFound = "No userRecord found",
  NoUserUriInSubject = "No user URI supplied in the subject block of SET",
  NotString = "Request is not a string",
  NotValidBase64 = "Request does not contain a valid Base64 string",
  NotValidEventType = "Event Type is not valid",
  NotValidJWSStructure = "Request does not contain a valid JWS. Invalid number of sections",
  TooManyMessages = "Too many messages are being attempting to be sent via SQS in one batch",
}
